@startuml
namespace po {
    interface Compiler  {
        + SetFile( *File) 
        + ToWriter( io.Writer) error
        + ToBytes() []byte

    }
    class Entries << (S,Aquamarine) >> {
        + Equal(e2 Entries) bool
        + Contains(c Entry) bool
        + ContainsUnifiedID(id string) bool
        + IndexByUnifiedID(uid string) int
        + Index(e2 Entry) int
        + IndexByIDAndCtx(id string, context string) int
        + IsSorted() bool
        + Sort() Entries
        + IsSortedByObsolete() bool
        + SortByObsolete() Entries
        + IsSortedByFuzzy() bool
        + SortByFuzzy() Entries
        + IsSortedByFile() bool
        + SortByFile() Entries
        + IsSortedByID() bool
        + SortByID() Entries
        + IsSortedByLine() bool
        + SortByLine() Entries
        + HasDuplicates() bool
        + CleanObsoletes() Entries
        + CleanDuplicates() Entries
        + Solve() Entries
        + CleanFuzzy() Entries
        + FuzzyFind(id string, context string) int
        + FuzzySolve() Entries
        + Header() Header

    }
    class Entry << (S,Aquamarine) >> {
        + Flags []string
        + Comments []string
        + ExtractedComments []string
        + Previous []string
        + Obsolete bool
        + ID string
        + Context string
        + Plural string
        + Plurals PluralEntries
        + Str string
        + Locations Locations

        + Validate() error
        + UnifiedStr() string
        + UnifiedID() string
        + Equal(x Entry) bool
        + IsPlural() bool
        + HasContext() bool
        + IsFuzzy() bool
        + String() string

    }
    class File << (S,Aquamarine) >> {
        + Entries Entries
        + Name string

        + Validate() error
        + Equal(f2 File) bool
        + Header() Header
        + Set(id string, context string, e Entry) 
        + LoadByUnifiedID(uid string) string
        + Load(id string, context string) string
        + MergeWithConfig(config MergeConfig, files ...*File) *File
        + MergeWithOptions(files []*File, options ...MergeOption) *File
        + Merge(files ...*File) *File

    }
    class Header << (S,Aquamarine) >> {
        + Fields []HeaderField

        + Nplurals() uint
        + ToEntry() Entry
        + Register(key string, d ...string) 
        + Load(key string) string
        + Set(key string, value string) 

    }
    class HeaderConfig << (S,Aquamarine) >> {
        + Nplurals uint
        + ProjectIDVersion string
        + ReportMsgidBugsTo string
        + Language string
        + LanguageTeam string
        + LastTranslator string

        + ToHeaderWithDefaults() Header
        + ToHeader() Header

    }
    class HeaderField << (S,Aquamarine) >> {
        + Key string
        + Value string

    }
    class Location << (S,Aquamarine) >> {
        + Line int
        + File string

        + Equal(l2 Location) bool

    }
    class Locations << (S,Aquamarine) >> {
        + Equal(l2 Locations) bool
        + Sort() Locations
        + SortByLine() Locations
        + SortByFile() Locations

    }
    class MergeConfig << (S,Aquamarine) >> {
        + FuzzyMatch bool
        + KeepPreviousIDs bool
        + Sort bool
        + SortMode SortMode

        + ApplyOption(opts ...MergeOption) 

    }
    interface Parser  {
        + Parse() *File
        + Error() error
        + Errors() []error

    }
    class PluralEntries << (S,Aquamarine) >> {
        + Equal(p2 PluralEntries) bool
        + Solve() PluralEntries
        + Sort() PluralEntries

    }
    class PluralEntry << (S,Aquamarine) >> {
        + ID int
        + Str string

        + Equal(p2 PluralEntry) bool

    }
    class SortMode << (S,Aquamarine) >> {
        + SortMethod(entries Entries) <font color=blue>func</font>() Entries

    }
    class po.Entries << (T, #FF7700) >>  {
    }
    class po.HeaderOption << (T, #FF7700) >>  {
    }
    class po.Locations << (T, #FF7700) >>  {
    }
    class po.MergeOption << (T, #FF7700) >>  {
    }
    class po.PluralEntries << (T, #FF7700) >>  {
    }
    class po.SortMode << (T, #FF7700) >>  {
    }
}


"__builtin__.int" #.. "po.SortMode"
"po.<font color=blue>func</font>(*HeaderConfig) " #.. "po.HeaderOption"
"po.<font color=blue>func</font>(*MergeConfig) " #.. "po.MergeOption"
"po.[]Entry" #.. "po.Entries"
"po.[]Location" #.. "po.Locations"
"po.[]PluralEntry" #.. "po.PluralEntries"
@enduml
